<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Sequence</name>
   <tag></tag>
   <elementGuidId>c2f446c1-3459-4dc4-b304-bdf5d0778279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='p-t__create-sequence']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#p-t__create-sequence</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1d36f6d-35eb-452d-b352-bee9dc1222c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-t__create-sequence</value>
      <webElementGuid>7c6efae9-fa69-44c2-a69f-abc48318d11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18f29ad8-5f76-4af7-a6ef-5e367b013f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-solid btn-solid-primary btn-solid-md</value>
      <webElementGuid>ad8a1c20-edec-4f3e-a9e1-a482972538dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Sequence</value>
      <webElementGuid>f703365e-e421-4598-84c2-03faff316ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-t__create-sequence&quot;)</value>
      <webElementGuid>a0502eb5-1e3e-47f2-8dd3-d76ed990cf26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='p-t__create-sequence']</value>
      <webElementGuid>08a8621a-4df2-4b87-a8ff-7a99fe3b2b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[9]/div/main/div[2]/div/div/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>eaf08fe5-310e-4aa4-9db0-ac1e7918f596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>0ede2b8b-e003-4016-8bcd-8c45467c1222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'p-t__create-sequence' and @type = 'button' and (text() = 'Create Sequence' or . = 'Create Sequence')]</value>
      <webElementGuid>945f70c5-a4f2-4c07-9e19-53ccfb51d0e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
