<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AP</name>
   <tag></tag>
   <elementGuidId>184b265e-2854-4d28-8552-a7839c81ad3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[9]/div/main/div/div[2]/span[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.align-items-center.pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43fedae4-0e26-4016-ade3-25cb5bcb2a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center pointer</value>
      <webElementGuid>218530c6-33ff-4851-bd1c-feb43bcf22c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d3fe397-aedb-48e2-a60d-697b2ba421cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c2cd5a4a-410d-449a-8e78-2b441dba1709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AP</value>
      <webElementGuid>08dfe8fb-74fd-49ae-9f4c-9ef6161b25e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;p-0  container-fluid&quot;]/div[@class=&quot;m-0 row&quot;]/main[@class=&quot;home-container&quot;]/div[@class=&quot;page-header row&quot;]/div[@class=&quot;text-right justify-content-end align-items-center d-flex p-0 col-md-8&quot;]/span[6]/div[@class=&quot;d-flex align-items-center pointer&quot;]</value>
      <webElementGuid>cc36e98f-4718-4afe-9eb1-7ef2ca4cac8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[9]/div/main/div/div[2]/span[6]/div</value>
      <webElementGuid>9fd93024-0f6c-497c-9ca4-3b7db6a30b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/div</value>
      <webElementGuid>201236e8-2dc4-4796-90d5-1ae1e2c587f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AP' or . = 'AP')]</value>
      <webElementGuid>7e27d2fe-dc95-414f-8924-f73d68f14956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
