<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Welcome Back to SaleshandyWork EmailPas_96be93</name>
   <tag></tag>
   <elementGuidId>c8e15734-f2fd-44a7-900f-b1b09bb751cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[9]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.auth-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a4f5922-77ef-4ffe-84a7-5532ee6a6a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-container</value>
      <webElementGuid>9e0bc4f2-8343-44b1-9628-63e91de4b441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome Back to SaleshandyWork EmailPasswordForgot Password?LoginDon’t have an account? Sign up!</value>
      <webElementGuid>409f33d6-725e-4850-b9ed-3521f9dd583d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;auth&quot;]/div[@class=&quot;auth-wrapper&quot;]/div[@class=&quot;auth-container&quot;]</value>
      <webElementGuid>0af83e02-8e9e-4382-af9a-dc4bfe950c25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[9]/div[2]/div</value>
      <webElementGuid>6c597993-2c2c-4ebf-b15e-9739ed9f4627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>8c314bb2-8a1a-4b90-a01c-e9685c88a791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Welcome Back to SaleshandyWork EmailPasswordForgot Password?LoginDon’t have an account? Sign up!' or . = 'Welcome Back to SaleshandyWork EmailPasswordForgot Password?LoginDon’t have an account? Sign up!')]</value>
      <webElementGuid>a1541c7b-0901-47ca-acbe-9c643b5112bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
