<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log Out</name>
   <tag></tag>
   <elementGuidId>79d791a5-337b-4b56-9ad3-ba193c99ec75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[9]/div/main/div/div[2]/span[6]/div/div/ul/li[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.align-items-center.px-3.profile-border-top.align-items-center.py-2.profile-cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22c85c3b-7306-4baf-a77e-bbf1633483bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center px-3 profile-border-top align-items-center py-2 profile-cursor-pointer</value>
      <webElementGuid>88758ae5-9ec7-4738-bcfd-f64bbf7890dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32dd9b17-a240-4611-8694-470a560e6139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1f57cc1b-2572-4f4f-8e8e-17aec57f2f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Out</value>
      <webElementGuid>dcb44a03-0826-448e-b858-8d85b797f2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;p-0  container-fluid&quot;]/div[@class=&quot;m-0 row&quot;]/main[@class=&quot;home-container&quot;]/div[@class=&quot;page-header row&quot;]/div[@class=&quot;text-right justify-content-end align-items-center d-flex p-0 col-md-8&quot;]/span[6]/div[@class=&quot;d-flex align-items-center pointer&quot;]/div[@class=&quot;profile-dropdown-view&quot;]/ul[@class=&quot;list-unstyled profile-dropdown-hovered-list&quot;]/li[@class=&quot;mt-1 menu-item&quot;]/div[@class=&quot;d-flex align-items-center px-3 profile-border-top align-items-center py-2 profile-cursor-pointer&quot;]</value>
      <webElementGuid>932c21c4-5bfd-4d48-9222-6e459793e47f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[9]/div/main/div/div[2]/span[6]/div/div/ul/li[6]/div</value>
      <webElementGuid>d13a1412-83a8-4907-83af-b1bc3566c36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP'])[2]/following::div[14]</value>
      <webElementGuid>66e3ed20-a1b3-44a2-95b6-7f26db9c2985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP'])[1]/following::div[17]</value>
      <webElementGuid>7cab625a-12e0-4d53-bf4c-298352e6742c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sequence Owner'])[1]/preceding::div[5]</value>
      <webElementGuid>8f1b9b49-e7c3-46af-8be5-311a0308c851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status (All)'])[1]/preceding::div[7]</value>
      <webElementGuid>12e4976b-4857-4f45-adcc-52c969573a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div</value>
      <webElementGuid>d390230b-7de0-4872-a496-fd17ce33eef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Log Out' or . = 'Log Out')]</value>
      <webElementGuid>3eadd2ce-4a4f-4f65-9893-52cd03bf74e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
